version: '2.1'
services:
  connector:
    # image: bh.cr/gh_phil_d_wilson/dapr
    build: ./connector
    privileged: true
    restart: always
    network_mode: host
    ports:
      - 8080:8080
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: '1'
    environment:
      - DEBUG=true
      - AZURE_BLOB_STORAGE_ACCOUNT_NAME=daprblockstorage
      - AZURE_BLOB_STORAGE_ACCOUNT_KEY=8hSrSzitwV8uhH+kEO4CEk8Voxm6C4FPW8XEDYr+e9ij7lJILregaJTp//4UX0I0BUa82TsG/wUm+AStUZcCdg==
      - AZURE_BLOB_CONTAINER_NAME=dapr-block
  mqtt:
    image: eclipse-mosquitto@sha256:307430eaf1e09ee4b7c8dbcd8303545be06431ee35fe43a9abff33d0fc992579
    ports:
      - "1883:1883"
    restart: always
  influxdb:
    image: influxdb:1.8.10
    ports:
      - "8086:8086"
    restart: always
    environment:
      - INFLUXDB_DB=balena
